<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="4334" started-at="2019-09-21T07:11:04Z" finished-at="2019-09-21T07:11:08Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="4334" started-at="2019-09-21T07:11:04Z" finished-at="2019-09-21T07:11:08Z">
      <class name="com.main.TestApplication">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.main.TestApplication@5315b42e]" name="setup" is-config="true" duration-ms="30" started-at="2019-09-21T12:41:04Z" finished-at="2019-09-21T12:41:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getApplicationResponse()[pri:0, instance:com.main.TestApplication@5315b42e]" name="getApplicationResponse" is-config="true" duration-ms="4267" started-at="2019-09-21T12:41:04Z" finished-at="2019-09-21T12:41:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getApplicationResponse -->
        <test-method status="FAIL" signature="testApplicationResponse(java.lang.String, java.lang.Object)[pri:0, instance:com.main.TestApplication@5315b42e]" name="testApplicationResponse" duration-ms="3" started-at="2019-09-21T12:41:08Z" data-provider="Test1DataProvider" finished-at="2019-09-21T12:41:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Path]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Invalid value]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Value for Key Path is not matching in application response. expected [Invalid value] but found [/Business-farming-industry/Carbon-credits]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Value for Key Path is not matching in application response. expected [Invalid value] but found [/Business-farming-industry/Carbon-credits]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.main.TestApplication.testApplicationResponse(TestApplication.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApplicationResponse -->
        <test-method status="PASS" signature="testApplicationResponse(java.lang.String, java.lang.Object)[pri:0, instance:com.main.TestApplication@5315b42e]" name="testApplicationResponse" duration-ms="6" started-at="2019-09-21T12:41:08Z" data-provider="Test1DataProvider" finished-at="2019-09-21T12:41:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Promotions]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[{"Description":"Good position in category \n2x larger image in desktop site search results","Name":"Gallery"}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApplicationResponse -->
        <test-method status="PASS" signature="testApplicationResponse(java.lang.String, java.lang.Object)[pri:0, instance:com.main.TestApplication@5315b42e]" name="testApplicationResponse" duration-ms="1" started-at="2019-09-21T12:41:08Z" data-provider="Test1DataProvider" finished-at="2019-09-21T12:41:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CanRelist]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApplicationResponse -->
        <test-method status="FAIL" signature="testApplicationResponse(java.lang.String, java.lang.Object)[pri:0, instance:com.main.TestApplication@5315b42e]" name="testApplicationResponse" duration-ms="1" started-at="2019-09-21T12:41:08Z" data-provider="Test1DataProvider" finished-at="2019-09-21T12:41:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Invalid_key]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Carbon credits]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Key Invalid_key is not available in application response expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Key Invalid_key is not available in application response expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.main.TestApplication.testApplicationResponse(TestApplication.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApplicationResponse -->
        <test-method status="PASS" signature="testApplicationResponse(java.lang.String, java.lang.Object)[pri:0, instance:com.main.TestApplication@5315b42e]" name="testApplicationResponse" duration-ms="1" started-at="2019-09-21T12:41:08Z" data-provider="Test1DataProvider" finished-at="2019-09-21T12:41:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Name]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Carbon credits]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApplicationResponse -->
      </class> <!-- com.main.TestApplication -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
